enabled: true
disabledWorlds:
  - "not_cleaned_world"
finishMessage: "<green>生物清理完成, 已清理{clean}/{all}</green>"
settings:
  cleanNamed: false
  cleanLeashed: false
  cleanMounted: false
blacklistMode: true
matchers:
  - "BLAZE"
  - "EVOKER"
  - "GHAST"
  - "(GLOW_)?SQUID"
  - "PHANTOM"
  - "PILLAGER"
